INSERT INTO studies_module (code, name, year) VALUES ('CI360', 'Mobile Application Development', '3');
INSERT INTO studies_module (code, name, year) VALUES ('CI347', 'Web & Network Management', '3');
INSERT INTO studies_module (code, name, year) VALUES ('CI346', 'Programming Languages, Concurrency', '3');
INSERT INTO studies_module (code, name, year) VALUES ('CI301', 'Individual Project', '3');
INSERT INTO studies_module (code, name, year) VALUES ('CI311', 'Specification & Refinement', '3');
INSERT INTO studies_module (code, name, year) VALUES ('CI209', 'Computer Systems Architecture', '2');
INSERT INTO studies_module (code, name, year) VALUES ('CI284', 'Data Structures & Algorithms', '2');
INSERT INTO studies_module (code, name, year) VALUES ('CI204', 'Databases II', '2');
INSERT INTO studies_module (code, name, year) VALUES ('CI231', 'Formal Underpinnings & Specification', '2');
INSERT INTO studies_module (code, name, year) VALUES ('CI233', 'Integrated Group Project', '2');
INSERT INTO studies_module (code, name, year) VALUES ('CI228', 'Object Oriented Software Design & Implementation', '2');
INSERT INTO studies_module (code, name, year) VALUES ('CI222', 'Project Planning and Control', '2');
INSERT INTO studies_module (code, name, year) VALUES ('CI', 'School', '3');